# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "lokka-sh"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["daichi"]
  s.date = "2012-02-01"
  s.description = "The Lokka Shell to execute sub commands of rails quickly."
  s.email = "bunny.hop.md@gmail.com"
  s.executables = ["lokka-sh"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/lokka-sh",
    "lib/lokka/sh.rb",
    "lib/lokka/sh/color.rb",
    "lib/lokka/sh/bundler.rb",
    "lib/lokka/sh/command.rb",
    "lib/lokka/sh/commands.rb",
    "lib/lokka/sh/forkable.rb",
    "lib/lokka/sh/helpers.rb",
    "lib/lokka/sh/sinatra.rb",
    "lib/lokka/sh/rake.rb",
    "lokka-sh.gemspec",
    "spec/lokka/sh/command_spec.rb",
    "spec/lokka/sh_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/daic-h/lokka-sh"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "The Lokka Shell"
  s.test_files = [
    "spec/lokka/sh/command_spec.rb",
    "spec/lokka/sh_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, ["= 0.8.7"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rake>, ["= 0.8.7"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, ["= 0.8.7"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

